apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-service
  namespace: devo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: consumer-service
  template:
    metadata:
      labels:
        app: consumer-service
    spec:
      containers:
      - name: consumer-service-container
        image: clustercr604613db7d.azurecr.io/dummy_service/dummy_service:1.0.0
        imagePullPolicy: "Always"
        command: ["/service/consumer-service"]
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: consumer-service
  namespace: devo
spec:
  selector:
    app: consumer-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
