apiVersion: apps/v1
kind: Deployment
metadata:
  name: service3
  namespace: devo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service3
  template:
    metadata:
      labels:
        app: service3
    spec:
      containers:
      - name: service3-container
        image: clustercr604613db7d.azurecr.io/dummy_service/dummy_service:1.0.0
        imagePullPolicy: "Always"
        command: ["/service/dummy-service"]
        args: ["service_3"]
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: service3
  namespace: devo
spec:
  selector:
    app: service3
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
